minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@vuepress-plume/plugin-fonts@1.0.0-rc.211'
  - '@vuepress-plume/plugin-search@1.0.0-rc.211'
  - vuepress-plugin-md-power@1.0.0-rc.211
  - vuepress-theme-plume@1.0.0-rc.211

trustPolicy: no-downgrade
shamefullyHoist: true
shellEmulator: true

overrides:
  '@vueuse/core': ^14.4.0
  esbuild: ^0.28.2
  markdown-it: 15.0.2
  vite: ^8.3.0
  vue: ^3.5.42

allowBuilds:
  esbuild: true
