import { defineNoteConfig } from 'vuepress-theme-plume'

export default defineNoteConfig({
  link: '/interview-question/',
  dir: '面试题',
  sidebar: [
    {
      dir: 'HTML',
      text: 'HTML',
      items: ['DOCTYPE', '元素的分类', 'HTML5新特性', '语义化理解'],
    },
    {
      dir: 'CSS',
      text: 'CSS',
      items: [
        '盒模型',
        '外边距合并',
        'BFC块级格式化上下文',
        'IFC,GFC,FFC',
        '像素',
        'CSS浮动',
        '元素垂直居中',
        'Flex弹性布局',
        'css三角形原理',
      ],
    },
    {
      dir: 'JavaScript',
      text: 'JavaScript',
      items: [
        '变量',
        '数据类型',
        '数据类型转换',
        '栈和堆',
        '原型和原型链',
        '执行上下文和执行栈',
        '作用域链',
        '闭包',
        '严格模式',
        '字符串',
        'NaN',
        '数组和对象',
        '集合对象',
        'this对象',
        '函数与箭头函数',
        'new操作符',
        '函数柯里化',
        '事件',
        '写一个通用事件侦听器',
        '模块化',
        '模块加载器原理',
        '浅拷贝和深拷贝',
        'DOM节点操作',
        '跨域',
        '节流与防抖',
        'promise',
        '设计模式',
        'MV-设计模式',
      ],
    },
    {
      dir: '浏览器',
      text: '浏览器',
      items: [
        '对浏览器的理解',
        '浏览器内核',
        '渲染原理',
        '浏览器解析过程',
        '浏览器渲染过程',
        '重绘与回流',
        '浏览器存储',
        '垃圾回收机制',
        '内存泄露',
        '事件循环',
        '浏览器输入URL',
      ],
    },
    {
      dir: '计算机网络',
      text: '计算机网络',
      items: ['http协议', 'http缓存', 'http2', 'TCP协议', 'UDP协议', 'CDN', '代理', '负载均衡'],
    },
    {
      dir: 'Vue',
      text: 'Vue',
      items: [
        'VirtualDom',
        'v-if和v-show的区别',
        'computed和watch',
        'keep-alive',
        'vue2和vue3的区别',
        '对vuex的理解',
        {
          text: 'vue@3',
          dir: 'v3',
          items: [
            '响应式原理',
            '组件通信方式',
            '生命周期',
            'v-model',
            'v-if和v-for优先级',
            '指令',
            '路由',
            'nextTick',
            'watch-watchEffect',
          ],
        },
        {
          text: 'vue@2',
          dir: 'v2',
          items: [
            '响应式原理',
            'data为什么必须是函数',
            'v-if和v-for优先级',
            '组件通信方式',
            '生命周期',
            '指令',
            '路由',
          ],
        },
      ],
    },
    {
      dir: 'React',
      text: 'React',
      items: [],
    },
    {
      dir: 'NodeJs',
      text: 'NodeJs',
      items: [],
    },
    {
      dir: '工具',
      text: '工具',
      items: ['git', 'git-hook', 'jenkins', '代码检查工具', '模块打包器', 'webpack', 'pm2'],
    },
    {
      dir: '常用库',
      text: '常用库',
      items: ['axios', 'lodash', 'UI框架'],
    },
    {
      dir: '安全',
      text: '安全',
      items: ['XSS攻击', 'CSRF攻击', 'SQL注入攻击', 'CSP内容安全', '点击劫持'],
    },
    {
      dir: '算法',
      text: '算法',
      items: [
        {
          text: '排序算法',
          dir: '排序',
          items: ['冒泡排序', '选择排序', '插入排序', '希尔排序', '归并排序', '快速排序', '排序算法总结'],
        },
      ],
    },
    {
      dir: '其他',
      text: '其他',
      items: ['前端SEO', '前端性能优化'],
    },
  ],
})
